export default [
  {
    id: '1',
    image: require('@/assets/img/user/avatars/1.png'),
    name: 'Jane Hew',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '2',
    image: require('@/assets/img/user/avatars/2.png'),
    name: 'Axel Pittman',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '3',
    image: require('@/assets/img/user/avatars/3.png'),
    name: 'Sophia Fernandez',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '4',
    image: require('@/assets/img/user/avatars/4.png'),
    name: 'Bob Nilson',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '5',
    image: require('@/assets/img/user/avatars/5.png'),
    name: 'Jessica Nilson',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '6',
    image: require('@/assets/img/user/avatars/1.png'),
    name: 'Jane Hew',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '7',
    image: require('@/assets/img/user/avatars/2.png'),
    name: 'Axel Pittman',
    role: 'Admin',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: '1234',
  },
  {
    id: '8',
    image: require('@/assets/img/user/avatars/3.png'),
    name: 'Sophia Fernandez',
    role: 'User',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '9',
    image: require('@/assets/img/user/avatars/4.png'),
    name: 'Bob Nilson',
    role: 'Writer',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '10',
    image: require('@/assets/img/user/avatars/5.png'),
    name: 'Jessica Nilson',
    role: 'User',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '11',
    image: require('@/assets/img/user/avatars/1.png'),
    name: 'Jane Hew',
    role: 'User',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Active',
    create: '2020-06-07',
    actions: true,
  },
  {
    id: '12',
    image: require('@/assets/img/user/avatars/2.png'),
    name: 'Axel Pittman',
    role: 'Writer',
    company: 'Flatlogic',
    email: 'admin@flatlogic.com',
    status: 'Inactive',
    create: '2020-06-07',
    actions: true,
  },
]